### ISSUE TITLE
Doesn't work with inner structs

### ISSUE THREAD

**Issue by xerenahmed** [daniel7grant/redis-macros#2]
```rust
#[derive(FromRedisValue, ToRedisArgs, Debug, Clone)]
pub struct Permissible<T: FromRedisValue + ToRedisValue> {
    pub inner: T,
    pub permissions: Vec<String>
}
```

this won't work

```rs
error[E0107]: missing generics for struct `Permissible`
  --> src/app/model/mod.rs:79:12
   |
79 | pub struct Permissible<T> {
   |            ^^^^^^^^^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `T`
  --> src/app/model/mod.rs:79:12
   |
79 | pub struct Permissible<T> {
   |            ^^^^^^^^^^^ -
help: add missing generic argument
   |
79 | pub struct Permissible<T><T> {
   |                       +++
```

**Comment by daniel7grant** [comment]
I started looking into this issue, and it lead me down into a rabbithole. Apparently Serde derive macros work in a way that  generic parameters don't need to implement the traits explicitly (see [#964](https://github.com/serde-rs/serde/issues/964#issuecomment-310419911)). Instead they are adding an extra `where` clause to the implementation that adds a `T: Serialize` for every generic parameter.

I suppose we should follow this approach, however it would result in a lot of extra code, essentially copying serde's implementation. I will look into how we can import the logic from the serde crate.

**Comment by daniel7grant** [comment]
I worked it out with some help, now it is supposed to work with generic structs. Please note, that this currently only works with owned parameters (works with `String`, but not with `&str`), because of some limitations in serde and redis. This is however the same way redis works (e.g. you cannot `conn.get` into a `&str`), so I'm not particularly worried about it.

Closing this, as it's supposed to work with v0.2.1, feel free to reopen if you face any issues.
