### ISSUE TITLE
[Help] does this work with HashSet Commands ?

### ISSUE THREAD

**Issue by nabeel99** [daniel7grant/redis-macros#6]
Hey
I just wanted to know if this works with hgetall and hget (multiple specific fields) , for e.g if i have a  hashset on my redis server and i create a struct mapping the field names and setting their type to all String, will this be able to convert those redis internal Value into my struct ?
Idk if its a limitation or something am doing wrong as i have been able to succesfully deserialize a hashset into a corresponding struct, would love any pointers or if its a limitation pls confirm it.

**Comment by daniel7grant** [comment]
Hey Nabeel, no, this library only works with `string` and `json` types. JSON is usually better in most cases because it supports nested structs and other constructs, albeit with a slight performance cost.

If you insist on hashes, I recommend checking out the [redis-derive](https://crates.io/crates/redis-derive) crate, which does similar things then this crate, but saves to a hash.
